CREATE TABLE IF NOT EXISTS pages (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id              uuid REFERENCES sites(id) ON DELETE CASCADE,
  url                  text NOT NULL,
  post_id              integer,
  post_type            text,
  title_current        text,
  meta_desc_current    text,
  h1_current           text,
  schema_current       jsonb,
  canonical_current    text,
  is_money_page        boolean DEFAULT false,
  last_meta_changed_at timestamptz,
  gsc_impressions      integer,
  gsc_clicks           integer,
  gsc_ctr              numeric,
  gsc_position         numeric,
  gsc_top_queries      jsonb,
  audit_has_h1         boolean,
  audit_canonical_ok   boolean,
  audit_schema_ok      boolean,
  audit_lcp_score      text CHECK (audit_lcp_score IN ('good','needs_improvement','poor')),
  audit_cls_score      text CHECK (audit_cls_score IN ('good','needs_improvement','poor')),
  audit_inp_score      text CHECK (audit_inp_score IN ('good','needs_improvement','poor')),
  needs_meta_opt       boolean DEFAULT false,
  needs_schema_opt     boolean DEFAULT false,
  has_empty_meta       boolean DEFAULT false,
  last_synced_at       timestamptz,
  created_at           timestamptz DEFAULT now(),
  UNIQUE(site_id, url)
);
